---
#==============================================================================
# Ansible Galaxy Requirements
#==============================================================================
# Install required collections with:
# ansible-galaxy collection install -r requirements.yml

collections:
  - name: community.docker
    version: ">=3.0.0"
    source: https://galaxy.ansible.com

  - name: community.general
    version: ">=5.0.0"
    source: https://galaxy.ansible.com

  - name: ansible.posix
    version: ">=1.5.0"
    source: https://galaxy.ansible.com
